/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ActivityType = IDL.Variant({
  'run' : IDL.Null,
  'walk' : IDL.Null,
  'cycle' : IDL.Null,
});
export const Activity = IDL.Record({
  'id' : IDL.Text,
  'startTime' : IDL.Int,
  'activityType' : ActivityType,
  'endTime' : IDL.Int,
  'calories' : IDL.Float64,
  'isActive' : IDL.Bool,
  'steps' : IDL.Nat,
  'distanceKm' : IDL.Float64,
  'durationMinutes' : IDL.Float64,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const T__1 = IDL.Record({
  'id' : IDL.Text,
  'fat' : IDL.Float64,
  'fiber' : IDL.Float64,
  'sodium' : IDL.Float64,
  'carbs' : IDL.Float64,
  'calories' : IDL.Float64,
  'sugar' : IDL.Float64,
  'photo' : ExternalBlob,
  'protein' : IDL.Float64,
});
export const Set = IDL.Record({
  'rpe' : IDL.Opt(IDL.Float64),
  'weight' : IDL.Float64,
  'reps' : IDL.Nat,
});
export const Exercise = IDL.Record({
  'name' : IDL.Text,
  'sets' : IDL.Vec(Set),
});
export const Workout = IDL.Record({
  'id' : IDL.Text,
  'duration' : IDL.Nat,
  'date' : IDL.Int,
  'name' : IDL.Text,
  'exercises' : IDL.Vec(Exercise),
  'notes' : IDL.Text,
});
export const GoalType = IDL.Variant({
  'duration' : IDL.Null,
  'calories' : IDL.Null,
  'distance' : IDL.Null,
  'workoutsPerWeek' : IDL.Null,
  'steps' : IDL.Null,
});
export const T = IDL.Record({
  'id' : IDL.Text,
  'endDate' : IDL.Int,
  'goalType' : GoalType,
  'description' : IDL.Text,
  'progress' : IDL.Nat,
  'target' : IDL.Nat,
  'startDate' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'displayName' : IDL.Text,
  'units' : IDL.Variant({ 'metric' : IDL.Null, 'imperial' : IDL.Null }),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSteps' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteAllUserData' : IDL.Func([], [], []),
  'deleteGoal' : IDL.Func([IDL.Text], [], []),
  'deleteMeal' : IDL.Func([IDL.Text], [], []),
  'deleteWorkout' : IDL.Func([IDL.Text], [], []),
  'endActivity' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Float64, IDL.Float64, IDL.Float64],
      [Activity],
      [],
    ),
  'exportUserData' : IDL.Func(
      [],
      [
        IDL.Record({
          'meals' : IDL.Vec(T__1),
          'workouts' : IDL.Vec(Workout),
          'activities' : IDL.Vec(Activity),
          'goals' : IDL.Vec(T),
          'stepCount' : IDL.Nat,
        }),
      ],
      [],
    ),
  'getAllActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getGoals' : IDL.Func([], [IDL.Vec(T)], ['query']),
  'getMeals' : IDL.Func([], [IDL.Vec(T__1)], ['query']),
  'getProfile' : IDL.Func([], [UserProfile], ['query']),
  'getTotalSteps' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkouts' : IDL.Func([], [IDL.Vec(Workout)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveGoal' : IDL.Func([T], [], []),
  'saveMeal' : IDL.Func(
      [
        IDL.Text,
        ExternalBlob,
        IDL.Tuple(
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
          IDL.Float64,
        ),
      ],
      [],
      [],
    ),
  'saveWorkout' : IDL.Func([Workout], [], []),
  'startActivity' : IDL.Func([IDL.Text, ActivityType], [], []),
  'updateProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ActivityType = IDL.Variant({
    'run' : IDL.Null,
    'walk' : IDL.Null,
    'cycle' : IDL.Null,
  });
  const Activity = IDL.Record({
    'id' : IDL.Text,
    'startTime' : IDL.Int,
    'activityType' : ActivityType,
    'endTime' : IDL.Int,
    'calories' : IDL.Float64,
    'isActive' : IDL.Bool,
    'steps' : IDL.Nat,
    'distanceKm' : IDL.Float64,
    'durationMinutes' : IDL.Float64,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const T__1 = IDL.Record({
    'id' : IDL.Text,
    'fat' : IDL.Float64,
    'fiber' : IDL.Float64,
    'sodium' : IDL.Float64,
    'carbs' : IDL.Float64,
    'calories' : IDL.Float64,
    'sugar' : IDL.Float64,
    'photo' : ExternalBlob,
    'protein' : IDL.Float64,
  });
  const Set = IDL.Record({
    'rpe' : IDL.Opt(IDL.Float64),
    'weight' : IDL.Float64,
    'reps' : IDL.Nat,
  });
  const Exercise = IDL.Record({ 'name' : IDL.Text, 'sets' : IDL.Vec(Set) });
  const Workout = IDL.Record({
    'id' : IDL.Text,
    'duration' : IDL.Nat,
    'date' : IDL.Int,
    'name' : IDL.Text,
    'exercises' : IDL.Vec(Exercise),
    'notes' : IDL.Text,
  });
  const GoalType = IDL.Variant({
    'duration' : IDL.Null,
    'calories' : IDL.Null,
    'distance' : IDL.Null,
    'workoutsPerWeek' : IDL.Null,
    'steps' : IDL.Null,
  });
  const T = IDL.Record({
    'id' : IDL.Text,
    'endDate' : IDL.Int,
    'goalType' : GoalType,
    'description' : IDL.Text,
    'progress' : IDL.Nat,
    'target' : IDL.Nat,
    'startDate' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'displayName' : IDL.Text,
    'units' : IDL.Variant({ 'metric' : IDL.Null, 'imperial' : IDL.Null }),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSteps' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteAllUserData' : IDL.Func([], [], []),
    'deleteGoal' : IDL.Func([IDL.Text], [], []),
    'deleteMeal' : IDL.Func([IDL.Text], [], []),
    'deleteWorkout' : IDL.Func([IDL.Text], [], []),
    'endActivity' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Float64, IDL.Float64, IDL.Float64],
        [Activity],
        [],
      ),
    'exportUserData' : IDL.Func(
        [],
        [
          IDL.Record({
            'meals' : IDL.Vec(T__1),
            'workouts' : IDL.Vec(Workout),
            'activities' : IDL.Vec(Activity),
            'goals' : IDL.Vec(T),
            'stepCount' : IDL.Nat,
          }),
        ],
        [],
      ),
    'getAllActivities' : IDL.Func([], [IDL.Vec(Activity)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getGoals' : IDL.Func([], [IDL.Vec(T)], ['query']),
    'getMeals' : IDL.Func([], [IDL.Vec(T__1)], ['query']),
    'getProfile' : IDL.Func([], [UserProfile], ['query']),
    'getTotalSteps' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkouts' : IDL.Func([], [IDL.Vec(Workout)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveGoal' : IDL.Func([T], [], []),
    'saveMeal' : IDL.Func(
        [
          IDL.Text,
          ExternalBlob,
          IDL.Tuple(
            IDL.Float64,
            IDL.Float64,
            IDL.Float64,
            IDL.Float64,
            IDL.Float64,
            IDL.Float64,
            IDL.Float64,
          ),
        ],
        [],
        [],
      ),
    'saveWorkout' : IDL.Func([Workout], [], []),
    'startActivity' : IDL.Func([IDL.Text, ActivityType], [], []),
    'updateProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };