/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Activity {
  'id' : string,
  'startTime' : bigint,
  'activityType' : ActivityType,
  'endTime' : bigint,
  'calories' : number,
  'isActive' : boolean,
  'steps' : bigint,
  'distanceKm' : number,
  'durationMinutes' : number,
}
export type ActivityType = { 'run' : null } |
  { 'walk' : null } |
  { 'cycle' : null };
export interface Exercise { 'name' : string, 'sets' : Array<Set> }
export type ExternalBlob = Uint8Array;
export type GoalType = { 'duration' : null } |
  { 'calories' : null } |
  { 'distance' : null } |
  { 'workoutsPerWeek' : null } |
  { 'steps' : null };
export interface Set {
  'rpe' : [] | [number],
  'weight' : number,
  'reps' : bigint,
}
export interface T {
  'id' : string,
  'endDate' : bigint,
  'goalType' : GoalType,
  'description' : string,
  'progress' : bigint,
  'target' : bigint,
  'startDate' : bigint,
}
export interface T__1 {
  'id' : string,
  'fat' : number,
  'fiber' : number,
  'sodium' : number,
  'carbs' : number,
  'calories' : number,
  'sugar' : number,
  'photo' : ExternalBlob,
  'protein' : number,
}
export interface UserProfile {
  'displayName' : string,
  'units' : { 'metric' : null } |
    { 'imperial' : null },
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Workout {
  'id' : string,
  'duration' : bigint,
  'date' : bigint,
  'name' : string,
  'exercises' : Array<Exercise>,
  'notes' : string,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSteps' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteAllUserData' : ActorMethod<[], undefined>,
  'deleteGoal' : ActorMethod<[string], undefined>,
  'deleteMeal' : ActorMethod<[string], undefined>,
  'deleteWorkout' : ActorMethod<[string], undefined>,
  'endActivity' : ActorMethod<
    [string, bigint, number, number, number],
    Activity
  >,
  'exportUserData' : ActorMethod<
    [],
    {
      'meals' : Array<T__1>,
      'workouts' : Array<Workout>,
      'activities' : Array<Activity>,
      'goals' : Array<T>,
      'stepCount' : bigint,
    }
  >,
  'getAllActivities' : ActorMethod<[], Array<Activity>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getGoals' : ActorMethod<[], Array<T>>,
  'getMeals' : ActorMethod<[], Array<T__1>>,
  'getProfile' : ActorMethod<[], UserProfile>,
  'getTotalSteps' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkouts' : ActorMethod<[], Array<Workout>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveGoal' : ActorMethod<[T], undefined>,
  'saveMeal' : ActorMethod<
    [
      string,
      ExternalBlob,
      [number, number, number, number, number, number, number],
    ],
    undefined
  >,
  'saveWorkout' : ActorMethod<[Workout], undefined>,
  'startActivity' : ActorMethod<[string, ActivityType], undefined>,
  'updateProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];