/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Exercise {
    name: string;
    sets: Array<Set_>;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface T__1 {
    id: string;
    fat: number;
    fiber: number;
    sodium: number;
    carbs: number;
    calories: number;
    sugar: number;
    photo: ExternalBlob;
    protein: number;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Set_ {
    rpe?: number;
    weight: number;
    reps: bigint;
}
export interface Activity {
    id: string;
    startTime: bigint;
    activityType: ActivityType;
    endTime: bigint;
    calories: number;
    isActive: boolean;
    steps: bigint;
    distanceKm: number;
    durationMinutes: number;
}
export interface T {
    id: string;
    endDate: bigint;
    goalType: GoalType;
    description: string;
    progress: bigint;
    target: bigint;
    startDate: bigint;
}
export interface Workout {
    id: string;
    duration: bigint;
    date: bigint;
    name: string;
    exercises: Array<Exercise>;
    notes: string;
}
export interface UserProfile {
    displayName: string;
    units: Variant_metric_imperial;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum ActivityType {
    run = "run",
    walk = "walk",
    cycle = "cycle"
}
export enum GoalType {
    duration = "duration",
    calories = "calories",
    distance = "distance",
    workoutsPerWeek = "workoutsPerWeek",
    steps = "steps"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_metric_imperial {
    metric = "metric",
    imperial = "imperial"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addSteps(steps: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteAllUserData(): Promise<void>;
    deleteGoal(id: string): Promise<void>;
    deleteMeal(id: string): Promise<void>;
    deleteWorkout(id: string): Promise<void>;
    endActivity(id: string, steps: bigint, calories: number, distanceKm: number, durationMinutes: number): Promise<Activity>;
    exportUserData(): Promise<{
        meals: Array<T__1>;
        workouts: Array<Workout>;
        activities: Array<Activity>;
        goals: Array<T>;
        stepCount: bigint;
    }>;
    getAllActivities(): Promise<Array<Activity>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getGoals(): Promise<Array<T>>;
    getMeals(): Promise<Array<T__1>>;
    getProfile(): Promise<UserProfile>;
    getTotalSteps(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWorkouts(): Promise<Array<Workout>>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveGoal(goal: T): Promise<void>;
    saveMeal(id: string, photo: ExternalBlob, nutrition: [number, number, number, number, number, number, number]): Promise<void>;
    saveWorkout(workout: Workout): Promise<void>;
    startActivity(id: string, activityType: ActivityType): Promise<void>;
    updateProfile(profile: UserProfile): Promise<void>;
}
import type { Activity as _Activity, ActivityType as _ActivityType, Exercise as _Exercise, ExternalBlob as _ExternalBlob, GoalType as _GoalType, Set as _Set, T as _T, T__1 as _T__1, UserProfile as _UserProfile, UserRole as _UserRole, Workout as _Workout, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addSteps(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addSteps(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addSteps(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteAllUserData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAllUserData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAllUserData();
            return result;
        }
    }
    async deleteGoal(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGoal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGoal(arg0);
            return result;
        }
    }
    async deleteMeal(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMeal(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMeal(arg0);
            return result;
        }
    }
    async deleteWorkout(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteWorkout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteWorkout(arg0);
            return result;
        }
    }
    async endActivity(arg0: string, arg1: bigint, arg2: number, arg3: number, arg4: number): Promise<Activity> {
        if (this.processError) {
            try {
                const result = await this.actor.endActivity(arg0, arg1, arg2, arg3, arg4);
                return from_candid_Activity_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.endActivity(arg0, arg1, arg2, arg3, arg4);
            return from_candid_Activity_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async exportUserData(): Promise<{
        meals: Array<T__1>;
        workouts: Array<Workout>;
        activities: Array<Activity>;
        goals: Array<T>;
        stepCount: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.exportUserData();
                return from_candid_record_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportUserData();
            return from_candid_record_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllActivities(): Promise<Array<Activity>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllActivities();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllActivities();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGoals(): Promise<Array<T>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGoals();
                return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGoals();
            return from_candid_vec_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMeals(): Promise<Array<T__1>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMeals();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMeals();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_UserProfile_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_UserProfile_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTotalSteps(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalSteps();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalSteps();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkouts(): Promise<Array<Workout>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkouts();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkouts();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n41(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n41(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveGoal(arg0: T): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveGoal(to_candid_T_n44(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveGoal(to_candid_T_n44(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveMeal(arg0: string, arg1: ExternalBlob, arg2: [number, number, number, number, number, number, number]): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveMeal(arg0, await to_candid_ExternalBlob_n48(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveMeal(arg0, await to_candid_ExternalBlob_n48(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async saveWorkout(arg0: Workout): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveWorkout(to_candid_Workout_n49(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveWorkout(to_candid_Workout_n49(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async startActivity(arg0: string, arg1: ActivityType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.startActivity(arg0, to_candid_ActivityType_n57(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.startActivity(arg0, to_candid_ActivityType_n57(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(to_candid_UserProfile_n41(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(to_candid_UserProfile_n41(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_ActivityType_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ActivityType): ActivityType {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Activity_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Activity): Activity {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_Exercise_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Exercise): Exercise {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_GoalType_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GoalType): GoalType {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_Set_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Set): Set_ {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
async function from_candid_T__1_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T__1): Promise<T__1> {
    return await from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_T_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _T): T {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Workout_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Workout): Workout {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    startTime: bigint;
    activityType: _ActivityType;
    endTime: bigint;
    calories: number;
    isActive: boolean;
    steps: bigint;
    distanceKm: number;
    durationMinutes: number;
}): {
    id: string;
    startTime: bigint;
    activityType: ActivityType;
    endTime: bigint;
    calories: number;
    isActive: boolean;
    steps: bigint;
    distanceKm: number;
    durationMinutes: number;
} {
    return {
        id: value.id,
        startTime: value.startTime,
        activityType: from_candid_ActivityType_n12(_uploadFile, _downloadFile, value.activityType),
        endTime: value.endTime,
        calories: value.calories,
        isActive: value.isActive,
        steps: value.steps,
        distanceKm: value.distanceKm,
        durationMinutes: value.durationMinutes
    };
}
async function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    meals: Array<_T__1>;
    workouts: Array<_Workout>;
    activities: Array<_Activity>;
    goals: Array<_T>;
    stepCount: bigint;
}): Promise<{
    meals: Array<T__1>;
    workouts: Array<Workout>;
    activities: Array<Activity>;
    goals: Array<T>;
    stepCount: bigint;
}> {
    return {
        meals: await from_candid_vec_n15(_uploadFile, _downloadFile, value.meals),
        workouts: from_candid_vec_n19(_uploadFile, _downloadFile, value.workouts),
        activities: from_candid_vec_n29(_uploadFile, _downloadFile, value.activities),
        goals: from_candid_vec_n30(_uploadFile, _downloadFile, value.goals),
        stepCount: value.stepCount
    };
}
async function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    fat: number;
    fiber: number;
    sodium: number;
    carbs: number;
    calories: number;
    sugar: number;
    photo: _ExternalBlob;
    protein: number;
}): Promise<{
    id: string;
    fat: number;
    fiber: number;
    sodium: number;
    carbs: number;
    calories: number;
    sugar: number;
    photo: ExternalBlob;
    protein: number;
}> {
    return {
        id: value.id,
        fat: value.fat,
        fiber: value.fiber,
        sodium: value.sodium,
        carbs: value.carbs,
        calories: value.calories,
        sugar: value.sugar,
        photo: await from_candid_ExternalBlob_n18(_uploadFile, _downloadFile, value.photo),
        protein: value.protein
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    duration: bigint;
    date: bigint;
    name: string;
    exercises: Array<_Exercise>;
    notes: string;
}): {
    id: string;
    duration: bigint;
    date: bigint;
    name: string;
    exercises: Array<Exercise>;
    notes: string;
} {
    return {
        id: value.id,
        duration: value.duration,
        date: value.date,
        name: value.name,
        exercises: from_candid_vec_n22(_uploadFile, _downloadFile, value.exercises),
        notes: value.notes
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    sets: Array<_Set>;
}): {
    name: string;
    sets: Array<Set_>;
} {
    return {
        name: value.name,
        sets: from_candid_vec_n25(_uploadFile, _downloadFile, value.sets)
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rpe: [] | [number];
    weight: number;
    reps: bigint;
}): {
    rpe?: number;
    weight: number;
    reps: bigint;
} {
    return {
        rpe: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.rpe)),
        weight: value.weight,
        reps: value.reps
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    endDate: bigint;
    goalType: _GoalType;
    description: string;
    progress: bigint;
    target: bigint;
    startDate: bigint;
}): {
    id: string;
    endDate: bigint;
    goalType: GoalType;
    description: string;
    progress: bigint;
    target: bigint;
    startDate: bigint;
} {
    return {
        id: value.id,
        endDate: value.endDate,
        goalType: from_candid_GoalType_n33(_uploadFile, _downloadFile, value.goalType),
        description: value.description,
        progress: value.progress,
        target: value.target,
        startDate: value.startDate
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: string;
    units: {
        metric: null;
    } | {
        imperial: null;
    };
}): {
    displayName: string;
    units: Variant_metric_imperial;
} {
    return {
        displayName: value.displayName,
        units: from_candid_variant_n38(_uploadFile, _downloadFile, value.units)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    run: null;
} | {
    walk: null;
} | {
    cycle: null;
}): ActivityType {
    return "run" in value ? ActivityType.run : "walk" in value ? ActivityType.walk : "cycle" in value ? ActivityType.cycle : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    duration: null;
} | {
    calories: null;
} | {
    distance: null;
} | {
    workoutsPerWeek: null;
} | {
    steps: null;
}): GoalType {
    return "duration" in value ? GoalType.duration : "calories" in value ? GoalType.calories : "distance" in value ? GoalType.distance : "workoutsPerWeek" in value ? GoalType.workoutsPerWeek : "steps" in value ? GoalType.steps : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    metric: null;
} | {
    imperial: null;
}): Variant_metric_imperial {
    return "metric" in value ? Variant_metric_imperial.metric : "imperial" in value ? Variant_metric_imperial.imperial : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_T__1>): Promise<Array<T__1>> {
    return await Promise.all(value.map(async (x)=>await from_candid_T__1_n16(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Workout>): Array<Workout> {
    return value.map((x)=>from_candid_Workout_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Exercise>): Array<Exercise> {
    return value.map((x)=>from_candid_Exercise_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Set>): Array<Set_> {
    return value.map((x)=>from_candid_Set_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Activity>): Array<Activity> {
    return value.map((x)=>from_candid_Activity_n10(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_T>): Array<T> {
    return value.map((x)=>from_candid_T_n31(_uploadFile, _downloadFile, x));
}
function to_candid_ActivityType_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityType): _ActivityType {
    return to_candid_variant_n58(_uploadFile, _downloadFile, value);
}
function to_candid_Exercise_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Exercise): _Exercise {
    return to_candid_record_n53(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_GoalType_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoalType): _GoalType {
    return to_candid_variant_n47(_uploadFile, _downloadFile, value);
}
function to_candid_Set_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Set_): _Set {
    return to_candid_record_n56(_uploadFile, _downloadFile, value);
}
function to_candid_T_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: T): _T {
    return to_candid_record_n45(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n42(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid_Workout_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Workout): _Workout {
    return to_candid_record_n50(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    displayName: string;
    units: Variant_metric_imperial;
}): {
    displayName: string;
    units: {
        metric: null;
    } | {
        imperial: null;
    };
} {
    return {
        displayName: value.displayName,
        units: to_candid_variant_n43(_uploadFile, _downloadFile, value.units)
    };
}
function to_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    endDate: bigint;
    goalType: GoalType;
    description: string;
    progress: bigint;
    target: bigint;
    startDate: bigint;
}): {
    id: string;
    endDate: bigint;
    goalType: _GoalType;
    description: string;
    progress: bigint;
    target: bigint;
    startDate: bigint;
} {
    return {
        id: value.id,
        endDate: value.endDate,
        goalType: to_candid_GoalType_n46(_uploadFile, _downloadFile, value.goalType),
        description: value.description,
        progress: value.progress,
        target: value.target,
        startDate: value.startDate
    };
}
function to_candid_record_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    duration: bigint;
    date: bigint;
    name: string;
    exercises: Array<Exercise>;
    notes: string;
}): {
    id: string;
    duration: bigint;
    date: bigint;
    name: string;
    exercises: Array<_Exercise>;
    notes: string;
} {
    return {
        id: value.id,
        duration: value.duration,
        date: value.date,
        name: value.name,
        exercises: to_candid_vec_n51(_uploadFile, _downloadFile, value.exercises),
        notes: value.notes
    };
}
function to_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    sets: Array<Set_>;
}): {
    name: string;
    sets: Array<_Set>;
} {
    return {
        name: value.name,
        sets: to_candid_vec_n54(_uploadFile, _downloadFile, value.sets)
    };
}
function to_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rpe?: number;
    weight: number;
    reps: bigint;
}): {
    rpe: [] | [number];
    weight: number;
    reps: bigint;
} {
    return {
        rpe: value.rpe ? candid_some(value.rpe) : candid_none(),
        weight: value.weight,
        reps: value.reps
    };
}
function to_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_metric_imperial): {
    metric: null;
} | {
    imperial: null;
} {
    return value == Variant_metric_imperial.metric ? {
        metric: null
    } : value == Variant_metric_imperial.imperial ? {
        imperial: null
    } : value;
}
function to_candid_variant_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GoalType): {
    duration: null;
} | {
    calories: null;
} | {
    distance: null;
} | {
    workoutsPerWeek: null;
} | {
    steps: null;
} {
    return value == GoalType.duration ? {
        duration: null
    } : value == GoalType.calories ? {
        calories: null
    } : value == GoalType.distance ? {
        distance: null
    } : value == GoalType.workoutsPerWeek ? {
        workoutsPerWeek: null
    } : value == GoalType.steps ? {
        steps: null
    } : value;
}
function to_candid_variant_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ActivityType): {
    run: null;
} | {
    walk: null;
} | {
    cycle: null;
} {
    return value == ActivityType.run ? {
        run: null
    } : value == ActivityType.walk ? {
        walk: null
    } : value == ActivityType.cycle ? {
        cycle: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Exercise>): Array<_Exercise> {
    return value.map((x)=>to_candid_Exercise_n52(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Set_>): Array<_Set> {
    return value.map((x)=>to_candid_Set_n55(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
